on:
  schedule:
    - cron:  '10 10 * * *'
name: Audit Org
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build
      uses: actions/npm@master
      with:
        entrypoint: npm
        args: install
    - name: Audit Teams 
      uses: actions/npm@master
      with:
        entrypoint: node
        args: teams.js
      env:
        GHTOKEN: ${{ secrets.GHTOKEN }}
