on:
  schedule:
    - cron:  '10 10 * * *'
name: Audit Org
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build
      run: npm install
    - name: Audit Teams 
      run: node teams.js
      env:
        GHTOKEN: ${{ secrets.GHTOKEN }}
